version: '3'
services:
  web:
    image: gitea/gitea:latest
    volumes:
      - ./gitea-data:/data
    ports:
      - "3000:3000"
      - "10022:10022"
    environment:
      - DB_TYPE=mysql
      - DB_HOST=db:40000
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
      - TZ=Japan
      - SSH_PORT=10022
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: mariadb:10
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
    ports:
      - 40000:3306
    volumes:
      - ./mysql-data:/var/lib/mysql

