version: '3'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx
    extra_hosts:
      # dockerホストマシンのipアドレスを使用する
      - "host.docker.internal:host-gateway"
    ports:
      - 443:443
    volumes:
      - ./config:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log/nginx
      - ./client_certificates:/etc/nginx/client_certificates
      - ./html:/var/www/html
