services:
  jenkinsmaster:
    container_name: jenkins
    image: jenkins/jenkins:latest
    restart: unless-stopped
    ports:
      - 8888:8080
      - 50000:50000
    environment:
      - JAVA_OPTS="-Duser.timezone=Asia/Tokyo" # 日本時間に
      - JENKINS_OPTS="--sessionTimeout=1440" # タイムアウト時間を延長
    volumes:
      # short syntaxを使用しバインドするフォルダ(orファイル)が存在しない場合、常にディレクトリが自動生成される。
      # また所有者はrootとなる。
      # そのためlong syntaxで記述するのが吉。
      - type: bind
        source: "./jenkins_home"
        target: "/var/jenkins_home"
          #- ./jenkins_home:/var/jenkins_home
